services:
  app:
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/production_db
      IP_STACK_API_ACCESS_KEY: ${IP_STACK_API_ACCESS_KEY}
      APP_ENV: production

  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: production_db
    container_name: production_db
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
