version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./tests:/tests

  db:
    image: postgres:14
    container_name: db
    restart: always
