services:
  app:
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/production_db
      APP_ENV: production

  db:
    environment:
      POSTGRES_DB: production_db
    container_name: production_db
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
